### ISSUE TITLE
How can I install and use this software?

### ISSUE THREAD

**Issue by sappelhoff** [hed-standard/CTagger#1]
I wanted to get started with tagging one of my datasets and based on the recent HED 3G whitepaper (https://osf.io/5fg73/), I searched for CTagger to help me with tagging (e.g., tag suggestions, maybe inbuilt validation of tags)

Based on the advertisement in the whitepaper (p 8 therein), I was expecting to find installation instructions for a standalone version (no Matlab or EEGLAB):

> A user-friendly GUI, CTagger (community tagger), initially developed for HED (1G) (Rognon et al. 2013), was further enhanced for HED (2G). CTagger is platform independent and can be run as a standalone application or as a plug-in for EEGLAB (Delorme and Makeig 2004). 

counter intuitively, there is some information in a repo that rather seems to supply some " Java tools for CTagger interface" (citing the repo description): https://github.com/hed-standard/hed-java

My questions are:

- what are all ways that I can install this software
- is it currently only for HED 1G and 2G?
- how exactly does the tool help me in tagging (what are its features?)

**Comment by dungscout96** [comment]
I updated the repo README with installation instruction and added some documentation on the Wiki to introduce its features. CTagger supports HED3. We really want people to stop using HED2 for their annotation. The tool's main feature is tag suggestion. Built-in validation is at the top of the TODO list next. Looking forward to hearing your feedbacks on it.

**Comment by VisLab** [comment]
@sappelhoff  Just a note:  some of the tagging suggestions are based on the `suggestedTag` and `relatedTag` attributes in the HED schema as well as descriptions of the nodes. This is a feature of the new HED-36.  Only a few of those are in the HED-3G schema (>= v8.0.0-alpha.1).  

We are in the process of making the transition to the new XML schema format (See [issue #155](https://github.com/hed-standard/hed-specification/issues/155) of hed-specification.) 

As soon as that is complete, we plan to go through the schema and put in `relatedTag` and `suggestTag` for many more nodes and improve the node descriptions.  This will be in HED schema v8.0.0-alpha.2.

**Comment by sappelhoff** [comment]
Awesome, thanks both. I'll try it out very soon.

**Comment by sappelhoff** [comment]
I gave it a try today, here is some feedback:

- I already had the Java runtime installed on my system (Ubuntu), running `java --version` yields the following for me:

```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
```

- I then downloaded `CTagger.jar`
- after making that "file" executable, I could run it via double click and/or right-click and "open with OpenJDK Java 11 Runtime"
- I can then see the initial "welcome" window with the three options (import spreadsheet, import dict, or quick tagging), see screenshot:

![image](https://user-images.githubusercontent.com/9084751/113690780-0f5a4100-96cc-11eb-90bd-ee6d7be7927f.png)


However, when clicking on "quick tagging" the program just closes, and no error messages are raised ... I also cannot see any log file, so I cannot share more information right now (unless you tell me where to look :slightly_smiling_face: )

The same thing happens for the other two buttons (spreadsheet, and dict) ... it lets me browse my file system to select an events.tsv or events.json file (respectively) but then upon double clicking on that file, the program closes (just as with quick tagging).

I am on an up to date Ubuntu 18.04 distribution, with the Java details mentioned above.

**Comment by dungscout96** [comment]
Turns out one of the library dependency is no longer included in the open-source Java runtime version 9 forward (I originally tested on JDK 8 for all Mac, Win, and CentOS). Java moved that library to the enterprise (paid) distribution. Kay raised the issue of Java being moved away from open-source awhile ago. I'll need to think more strategically on how I should move forward.

In the meantime, if possible you can try downgrading java version: https://askubuntu.com/questions/1133216/downgrading-java-11-to-java-8, or try using a virtual machine with fresh install of Java 8. I understand if you don't want to do that in case you have other software depending on Java 11.

**Comment by dungscout96** [comment]
@sappelhoff I have resolved the issue and tested it on Ubuntu with openjdk 11.0.11

**Comment by sappelhoff** [comment]
Thanks @dungscout96 - I gave this a spin today, and unfortunately it still closes unexpectedly, my report from above is the same ... except that I downloaded the new CTagger.jar from https://github.com/hed-standard/CTagger/raw/main/CTagger.jar

PS: Is there some error log that I could find on my machine and report to you?

**Comment by dungscout96** [comment]
I'm still not sure why it's not working on your end. I'm unable to replicate the issue myself. I did push some bug fixes so can you try downloading it again?
This time can you start the program through the terminal by executing `java -jar CTagger.jar` under the directory containing CTagger.jar?

That should print out the error messages.

Thank you for your patience!

**Comment by sappelhoff** [comment]
Running `java -jar CTagger.jar` with the new CTagger.jar (downloaded just now) worked!

This is the log I received after "quick tagging" (click on "details"):

<details>

```
code HED selected
code HED selected
Exception Position not represented by viewjavax.swing.text.BadLocationException: Position not represented by view
	at java.desktop/javax.swing.text.CompositeView.modelToView(CompositeView.java:277)
	at java.desktop/javax.swing.text.BoxView.modelToView(BoxView.java:485)
	at java.desktop/javax.swing.text.ParagraphView$Row.modelToView(ParagraphView.java:893)
	at java.desktop/javax.swing.text.CompositeView.modelToView(CompositeView.java:267)
	at java.desktop/javax.swing.text.BoxView.modelToView(BoxView.java:485)
	at java.desktop/javax.swing.text.CompositeView.modelToView(CompositeView.java:267)
	at java.desktop/javax.swing.text.BoxView.modelToView(BoxView.java:485)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.modelToView(BasicTextUI.java:1605)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1110)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1087)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1063)
	at java.desktop/javax.swing.text.JTextComponent.modelToView(JTextComponent.java:1392)
	at HedTagInput.insertUpdate(HedTagInput.kt:65)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
	at InputLayeredPane.insertTagAtCaret(InputLayeredPane.kt:97)
	at SchemaView.addTagToEditor(SchemaView.kt:104)
	at SchemaView$ml$1.mousePressed(SchemaView.kt:49)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

</details>

I don't know what fixes you pushed, but they did something, because now I can also double click the CTagger.jar and everything works.

**Comment by dungscout96** [comment]
Glad to hear that!

Which action did you perform right when the error happened?

**Comment by sappelhoff** [comment]
Which error? The old one?

**Comment by sappelhoff** [comment]
The one where I posted the details on did not break anything, that was during quick tagging but I don't remember the exact actions I did

**Comment by dungscout96** [comment]
The one in "details". I have some guess on what might have caused the error. But if you happen to encounter it again let me know!

Closing this issue now then.

**Comment by sappelhoff** [comment]
Thanks for the fixes and added documentation
